In [3]:
# 1 Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare?
#Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] # è una matrice o un array a due dimensioni
# per accerede a un elemento bisogna fare riferimento ai due indici della matrice
mat[0][1] # accede al secondo elemento della prima lista
mat[1][2] # accedere al terzo elemento della seconda lista
#mat[4][0] # dà errore perché non possiede una lista con indice 4

7

In [18]:
# 2 Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?

import math as m

a = 45
b = 90
c = 0

print(m.sin(a))
print(m.cos(a))
print(m.tan(a))
print(m.factorial(a))
print(m.sin(b))
print(m.cos(b))
print(m.tan(b))
print(m.factorial(b))
print(m.sin(c))
print(m.cos(c))
print(m.tan(c))
print(m.factorial(c))
print(m.pi)

0.8509035245341184
0.5253219888177297
1.6197751905438615
119622220865480194561963161495657715064383733760000000000
0.8939966636005579
-0.4480736161291701
-1.995200412208242
1485715964481761497309522733620825737885569961284688766942216863704985393094065876545992131370884059645617234469978112000000000000000000000
0.0
1.0
0.0
1
3.141592653589793


In [21]:
# 3 Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)

print(m.degrees(m.pi))
print(m.degrees(m.tau))
help(m.degrees)

180.0
360.0
Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [31]:
# 4
import numpy as np

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)

#qual è stata la vendita massima mensile? E quella minima?
lst_max = np.max(lst)
lst_min = np.min(lst)
print(lst_max, lst_min)
#• quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono?
filtro_5k = lst > 5000
print(lst[filtro_5k])
print(len(lst[filtro_5k]))
#• quali sono le vendite minori di 3000 oggetti?
filtro_3k = lst < 3000
print(lst[filtro_3k])
print(len(lst[filtro_3k]))
#• in media quanti oggetti sono stati venduti al mese?
avg_lst = np.mean(lst)
print(round(avg_lst), 1)

8150 1280
[5500 7200 6410 8150 7100 5350]
6
[2000 1280 1900 2500]
4
4634 1


In [15]:
# 5
import pandas as pd

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

print(fatturati_dict[1997], fatturati_series[1997])
print(fatturati_series[:3])

# La differenza tra dict e series è che il secondo è più efficiente nello storage delle informazioni, inoltre è possibile utilizzare gli indici non solo come 
# tag univoco ma gli indici possono essere ripetuti per permettere agrregazioni successive. I dizionari invece ammettono solo valori chiave univoci

12000 12000
1997    12000
1998    15000
1999    20000
dtype: int64


In [56]:
# 6 
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

# raddoppiare gli stipendi con il ciclo for

for i in range(len(stipendi)):
    stipendi[i] = stipendi[i]* 2
print(stipendi)

stipendi_doppi = stipendi * 2
print(stipendi_doppi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
[ 400  800 1200 1600 2000 2400 2800 3200 3600 4000]


In [3]:
# 7 Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; gestire il caso in cui la lista sia più corta di tre,
# e quando uno o più dei numeri selezionati sono uguali.
def max_three(numbers):
    if len(numbers) < 3:
        print('La lista è più corta di tre elementi')
        return []
    unique_numbers = set(numbers)
    unique_numbers_list = list(unique_numbers)
    unique_numbers_list.sort(reverse=True)
    return unique_numbers_list[:3]

numbers = [23, 44, 12, 67, 8, 34, 9, 43, 90, 44, 67, 23, 55, 1]
numbers_alt = [100, 99, 88, 88, 99]
print(max_three(numbers))
print(max_three(numbers_alt))

[90, 67, 55]
[100, 99, 88]


In [18]:
# 8 Scrivere un programma che • in input acquisisce una lista di numeri e un numero K 
#• in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
#• se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.
import numpy as np

def k_comparison(lst, k):
    lst = np.array(lst)
    numeri_maggio_k = []
    for num in lst:
        if num >= k:
            numeri_maggio_k.append(num)
    if len(numeri_maggio_k) > 0:
        media = np.array(numeri_maggio_k).mean()
        return media
    else: 
        print('Non ci sono valori maggiori di k')
        
user_answer = int(input('Quanti numeri vuoi inserire?'))
lst = []
for pos_lst in range(user_answer):
    prossimo_numero = int(input('Inserisci un numero'))
    lst.append(prossimo_numero)
                          
    
k = int(input('Scegli un numero'))

k_comparison(lst, k)

Quanti numeri vuoi inserire? 4
Inserisci un numero 1
Inserisci un numero 2
Inserisci un numero 3
Inserisci un numero 4
Scegli un numero 2


3.0

In [20]:
numeri = [5, 7, 4, 3, 6]

for num in numeri:
    print('*' * num)

*****
*******
****
***
******


In [6]:
# 10 

lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

lista_95 = []

for cf in lista_cf:
    for i in range(len(cf)-1):
        if cf[i] == '9' and cf[i+1] == '5':
            lista_95.append(cf)
print(lista_95)

# oppure

for cf in lista_cf:
    if '95' in cf:
        lista_95.append(cf)
print(lista_95)
        

['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G', 'ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [12]:
# Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente:

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

# Stampare a video tutti e soli gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.

lst_combined= []
for i in range(len(studenti)):
    lst_combined.append([studenti[i], edizioni[i]])
print(lst_combined)


[['Alex', 1], ['Bob', 2], ['Cindy', 3], ['Dan', 2], ['Emma', 2], ['Faith', 1], ['Grace', 3], ['Henry', 3]]
